USE [master]
GO

/****** Object:  Database [inventarioBodega]    Script Date: 07/04/2016 18:10:45 ******/
CREATE DATABASE [inventarioBodega] ON  PRIMARY 
( NAME = N'Inventario de Bodegas UNICAH', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\inventarioBodega.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Inventario de Bodegas UNICAH_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESS\MSSQL\DATA\inventarioBodega.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [inventarioBodega] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [inventarioBodega].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [inventarioBodega] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [inventarioBodega] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [inventarioBodega] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [inventarioBodega] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [inventarioBodega] SET ARITHABORT OFF 
GO

ALTER DATABASE [inventarioBodega] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [inventarioBodega] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [inventarioBodega] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [inventarioBodega] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [inventarioBodega] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [inventarioBodega] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [inventarioBodega] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [inventarioBodega] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [inventarioBodega] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [inventarioBodega] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [inventarioBodega] SET  DISABLE_BROKER 
GO

ALTER DATABASE [inventarioBodega] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [inventarioBodega] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [inventarioBodega] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [inventarioBodega] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [inventarioBodega] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [inventarioBodega] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [inventarioBodega] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [inventarioBodega] SET  READ_WRITE 
GO

ALTER DATABASE [inventarioBodega] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [inventarioBodega] SET  MULTI_USER 
GO

ALTER DATABASE [inventarioBodega] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [inventarioBodega] SET DB_CHAINING OFF 
GO

